# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ExpressPathToRegex"); Pkg.test("ExpressPathToRegex"; coverage=true)'
after_success:
    - julia -e 'if VERSION >= v"0.4-" && OS_NAME == :Linux; cd(Pkg.dir("ExpressPathToRegex")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); end'